Added first testinfra tests.

diff --git a/run-tests b/run-tests
--- a/run-tests
+++ b/run-tests
@@ -26,6 +26,20 @@ set -o pipefail
 #   }
 # }
 
+unexpected_exit()
+{
+    >&2 echo "Error: Unexpected exit!"
+    trap - EXIT
+    revert_sudoers
+    exit 1
+}
+
+revert_sudoers()
+{
+    echo "Reverting sudo password removal on ${DEVICE_IP}."
+    ssh -F "${SCRIPT_DIR}/no_host_key_checking" "${DEVICE_USER}@${DEVICE_IP}" 'sudo rm /etc/sudoers.d/pytest_no_passwd' > /dev/null 2>&1
+}
+
 if [ "$#" -ne 2 ]
 then
     >&2 echo "Error: Illegal number of arguments!"
@@ -69,9 +83,17 @@ echo "Retrieving IP address of ${DEVICE_ID}".
 DEVICE_IP=$("${SCRIPT_DIR}/mender-api" query "${DEVICE_ID}" "${DEVICE_INTERFACE}")
 DEVICE_IP="${DEVICE_IP%/*}"
 
-echo "Removing sudo password on ${DEVICE_IP}".
+trap unexpected_exit EXIT
+
+echo "Removing sudo password on ${DEVICE_IP}."
 ssh -F "${SCRIPT_DIR}/no_host_key_checking" "${DEVICE_USER}@${DEVICE_IP}" > /dev/null 2>&1 << EOF
-  echo "${DEVICE_USER} ALL=(ALL) NOPASSWD: ALL" > pytest_no_passwd
-  echo "${DEVICE_PASSWORD}" | sudo -S chown root:root pytest_no_passwd
-  echo "${DEVICE_PASSWORD}" | sudo -S mv pytest_no_passwd /etc/sudoers.d/ > /dev/null 2>&1
+    echo "${DEVICE_USER} ALL=(ALL) NOPASSWD: ALL" > pytest_no_passwd
+    echo "${DEVICE_PASSWORD}" | sudo -S chown root:root pytest_no_passwd
+    echo "${DEVICE_PASSWORD}" | sudo -S mv pytest_no_passwd /etc/sudoers.d/ > /dev/null 2>&1
 EOF
+
+echo "Running tests on ${DEVICE_IP}."
+py.test-3 --ssh-config="${SCRIPT_DIR}/no_host_key_checking" --hosts="${DEVICE_USER}@${DEVICE_IP}" --connection=ssh
+
+revert_sudoers
+trap - EXIT
